# Generated by Django 5.0.4 on 2024-04-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_address_customer_city_remove_customer_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
