# Generated by Django 5.0.4 on 2024-04-09 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(default='veg', max_length=500)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VendorApp.vendor')),
            ],
        ),
    ]
