# Generated by Django 5.0.4 on 2024-04-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0006_alter_food_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='vendor',
        ),
        migrations.AddField(
            model_name='food',
            name='Vendor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
