# Generated by Django 5.0.4 on 2024-04-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0007_remove_food_vendor_food_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
