# Generated by Django 5.0.4 on 2024-04-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0008_vendor_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
