# Generated by Django 5.0.4 on 2024-04-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0010_alter_vendor_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='Vendor_name',
        ),
        migrations.AddField(
            model_name='food',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VendorApp.vendor'),
        ),
    ]
