# Generated by Django 5.0.4 on 2024-04-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VendorApp", "0011_remove_food_vendor_name_food_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="region",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
