# Generated by Django 5.0.4 on 2024-04-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VendorApp", "0012_food_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="status",
        ),
        migrations.AddField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
