# Generated by Django 4.2.5 on 2024-04-13 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("VendorApp", "0014_remove_vendor_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food_single",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("main_category", models.CharField(max_length=500)),
                ("category", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="images")),
                ("price", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=500)),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("type", models.CharField(default="veg", max_length=500)),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="VendorApp.vendor",
                    ),
                ),
            ],
        ),
    ]
