# Generated by Django 4.2.5 on 2024-04-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("VendorApp", "0016_remove_food_single_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food_single",
            old_name="name",
            new_name="single_name",
        ),
    ]
