# Generated by Django 5.0.4 on 2024-04-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VendorApp", "0017_rename_name_food_single_single_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="average_rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
