# Generated by Django 5.0.4 on 2024-04-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VendorApp", "0018_vendor_average_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="food_single",
            name="average_rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
