# Generated by Django 5.0.4 on 2024-04-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VendorApp", "0020_remove_food_vendor_remove_food_single_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="region",
        ),
        migrations.AddField(
            model_name="food",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="VendorApp.vendor",
            ),
        ),
    ]
