# Generated by Django 5.0.4 on 2024-04-13 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VendorApp", "0022_food_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="food_single",
            name="vendor_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="VendorApp.vendor",
            ),
        ),
    ]
