# Generated by Django 5.0.4 on 2024-04-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("VendorApp", "0023_food_single_vendor_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food_single",
            old_name="vendor_id",
            new_name="vendor",
        ),
    ]
