# Generated by Django 5.0.4 on 2024-04-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("VendorApp", "0024_rename_vendor_id_food_single_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="price",
        ),
    ]
