# Generated by Django 5.0.4 on 2024-04-14 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VendorApp", "0025_remove_food_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="contact",
            field=models.CharField(
                max_length=10,
                null=True,
                validators=[django.core.validators.RegexValidator("^\\d{10}$")],
            ),
        ),
    ]
