# Generated by Django 5.0.4 on 2024-04-14 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VendorApp", "0026_alter_vendor_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="contact",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.RegexValidator("^\\d{10}$")],
            ),
        ),
    ]
