# Generated by Django 5.0.4 on 2024-04-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_db',
            name='user_type',
            field=models.CharField(choices=[('customer', 'customer'), ('vendor', 'vendor')], max_length=50, null=True),
        ),
    ]
