# Generated by Django 5.0.4 on 2024-04-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
