# Generated by Django 5.0.4 on 2024-04-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_db',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
