# Generated by Django 5.0.4 on 2024-04-12 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_remove_bookingdb_time_bookingdb_date'),
        ('VendorApp', '0011_remove_food_vendor_name_food_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_review_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_image', models.ImageField(blank=True, default='Images/usericon1.jpg', null=True, upload_to='reviewer_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.food')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_review_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_image', models.ImageField(blank=True, default='Images/usericon.jpg', null=True, upload_to='reviewer_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.vendor')),
            ],
        ),
    ]
