# Generated by Django 5.0.4 on 2024-04-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0011_orderitem_d_signup_db_is_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="d",
        ),
    ]
