# Generated by Django 5.0.4 on 2024-04-13 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0013_alter_vendor_review_db_review_text_and_more"),
        ("VendorApp", "0018_vendor_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_review_db",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="VendorApp.food_single"
            ),
        ),
        migrations.AlterField(
            model_name="food_review_db",
            name="username",
            field=models.TextField(max_length=100),
        ),
    ]
