# Generated by Django 5.0.4 on 2024-04-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0014_alter_food_review_db_food_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="vendor_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
