# Generated by Django 5.0.4 on 2024-04-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0015_orderitem_vendor_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="vendor_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
