# Generated by Django 5.0.4 on 2024-04-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0016_order_vendor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Order Confirmed", "Order Confirmed"),
                    ("Order Processing", "Order Processing"),
                    ("Out for delivery", "Out for delivery"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Order Confirmed",
                max_length=50,
            ),
        ),
    ]
