# Generated by Django 5.0.4 on 2024-04-14 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0017_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingdb",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bookingdb",
            name="mobile_number",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.RegexValidator("^\\d{10}$")],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.RegexValidator("^\\d{10}$")],
            ),
        ),
    ]
