# Generated by Django 5.0.4 on 2024-04-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "UserApp",
            "0018_alter_bookingdb_email_alter_bookingdb_mobile_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
