# Generated by Django 5.0.4 on 2024-04-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0019_order_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup_db",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="signup_db",
            name="token_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
